"""updates

Revision ID: 2091e1a98747
Revises: e2ec8d5e55c8
Create Date: 2025-10-08 12:12:54.232509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2091e1a98747'
down_revision: Union[str, Sequence[str], None] = 'e2ec8d5e55c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('advertisement_photos_photo_id_fkey'), 'advertisement_photos', type_='foreignkey')
    op.drop_constraint(op.f('advertisement_photos_advertisement_id_fkey'), 'advertisement_photos', type_='foreignkey')
    op.create_foreign_key(None, 'advertisement_photos', 'photos', ['photo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'advertisement_photos', 'advertisements', ['advertisement_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('advertisements_user_role_id_fkey'), 'advertisements', type_='foreignkey')
    op.drop_constraint(op.f('advertisements_type_advertisement_id_fkey'), 'advertisements', type_='foreignkey')
    op.drop_constraint(op.f('advertisements_location_id_fkey'), 'advertisements', type_='foreignkey')
    op.create_foreign_key(None, 'advertisements', 'user_roles', ['user_role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'advertisements', 'type_advertisements', ['type_advertisement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'advertisements', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('applications_advertisement_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_user_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'advertisements', ['advertisement_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('favorites_user_id_fkey'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('favorites_advertisement_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'advertisements', ['advertisement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('locations_street_id_fkey'), 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'streets', ['street_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('streets_city_id_fkey'), 'streets', type_='foreignkey')
    op.create_foreign_key(None, 'streets', 'cities', ['city_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_logos_user_id_fkey'), 'user_logos', type_='foreignkey')
    op.drop_constraint(op.f('user_logos_logo_id_fkey'), 'user_logos', type_='foreignkey')
    op.create_foreign_key(None, 'user_logos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_logos', 'logos', ['logo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_roles_role_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_user_id_fkey'), 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_roles_role_id_fkey'), 'user_roles', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'user_logos', type_='foreignkey')
    op.drop_constraint(None, 'user_logos', type_='foreignkey')
    op.create_foreign_key(op.f('user_logos_logo_id_fkey'), 'user_logos', 'logos', ['logo_id'], ['id'])
    op.create_foreign_key(op.f('user_logos_user_id_fkey'), 'user_logos', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'streets', type_='foreignkey')
    op.create_foreign_key(op.f('streets_city_id_fkey'), 'streets', 'cities', ['city_id'], ['id'])
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(op.f('locations_street_id_fkey'), 'locations', 'streets', ['street_id'], ['id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_advertisement_id_fkey'), 'favorites', 'advertisements', ['advertisement_id'], ['id'])
    op.create_foreign_key(op.f('favorites_user_id_fkey'), 'favorites', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_user_id_fkey'), 'applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('applications_advertisement_id_fkey'), 'applications', 'advertisements', ['advertisement_id'], ['id'])
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.create_foreign_key(op.f('advertisements_location_id_fkey'), 'advertisements', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('advertisements_type_advertisement_id_fkey'), 'advertisements', 'type_advertisements', ['type_advertisement_id'], ['id'])
    op.create_foreign_key(op.f('advertisements_user_role_id_fkey'), 'advertisements', 'user_roles', ['user_role_id'], ['id'])
    op.drop_constraint(None, 'advertisement_photos', type_='foreignkey')
    op.drop_constraint(None, 'advertisement_photos', type_='foreignkey')
    op.create_foreign_key(op.f('advertisement_photos_advertisement_id_fkey'), 'advertisement_photos', 'advertisements', ['advertisement_id'], ['id'])
    op.create_foreign_key(op.f('advertisement_photos_photo_id_fkey'), 'advertisement_photos', 'photos', ['photo_id'], ['id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('topology',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('topology_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hasz', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='topology_pkey'),
    sa.UniqueConstraint('name', name='topology_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('layer',
    sa.Column('topology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_column', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topology.id'], name=op.f('layer_topology_id_fkey')),
    sa.PrimaryKeyConstraint('topology_id', 'layer_id', name=op.f('layer_pkey')),
    sa.UniqueConstraint('schema_name', 'table_name', 'feature_column', name=op.f('layer_schema_name_table_name_feature_column_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
