"""update_model_advertisement

Revision ID: 503b2f21bd92
Revises: 7ca9b178e518
Create Date: 2025-07-11 14:52:55.770431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503b2f21bd92'
down_revision: Union[str, Sequence[str], None] = '7ca9b178e518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'price')
    # ### end Alembic commands ###
