"""update_ads

Revision ID: 6fac41400eb8
Revises: a25436c0fffb
Create Date: 2025-08-07 12:05:50.002466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fac41400eb8'
down_revision: Union[str, Sequence[str], None] = 'a25436c0fffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisements', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisements', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
