"""update_model_advertisement

Revision ID: cb70e06a3e0a
Revises: 503b2f21bd92
Create Date: 2025-07-11 15:04:13.724648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb70e06a3e0a'
down_revision: Union[str, Sequence[str], None] = '503b2f21bd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('from_the_date', sa.Date(), nullable=False))
    op.add_column('advertisements', sa.Column('before_the_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'before_the_date')
    op.drop_column('advertisements', 'from_the_date')
    # ### end Alembic commands ###
